(()=>{
  "use strict";
  const DATA=window.EXAM_FAST_DATA, KEY="exam-fast-progress-v1", $=(s,r=document)=>r.querySelector(s), esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
  const defaultState=()=>({progress:{},mistakes:{},xp:0,started:new Date().toISOString()});
  let state;try{state={...defaultState(),...JSON.parse(localStorage.getItem(KEY)||"{}")}}catch{state=defaultState()}
  let session=null;
  const save=()=>localStorage.setItem(KEY,JSON.stringify(state));
  const prog=id=>state.progress[id]||{attempts:0,correct:0,wrong:0,streak:0,last:null};
  const safe=()=>DATA.questions.filter(q=>q.correctAnswer&&q.answers?.[q.correctAnswer]);
  const qmap=new Map(DATA.questions.map(q=>[q.id,q]));
  function metrics(){const qs=safe(),seen=qs.filter(q=>prog(q.id).attempts),attempts=qs.reduce((n,q)=>n+prog(q.id).attempts,0),correct=qs.reduce((n,q)=>n+prog(q.id).correct,0),mastered=qs.filter(q=>prog(q.id).streak>=3);return{total:qs.length,seen:seen.length,coverage:Math.round(seen.length/qs.length*100),accuracy:attempts?Math.round(correct/attempts*100):null,mastered:mastered.length,attempts}}
  function chrome(){const m=metrics();$("#coverage").textContent=`Coverage ${m.coverage}%`;$("#accuracy").textContent=`Skuteczność ${m.accuracy??"—"}${m.accuracy===null?"":"%"}`;document.querySelectorAll(".nav a").forEach(a=>a.classList.toggle("active",a.hash===location.hash))}
  function weighted(pool){return pool.map(q=>{const p=prog(q.id),mist=state.mistakes[q.id]?.count||0;return{q,w:Math.max(1,(q.priority||1)*2+(p.attempts?0:12)+mist*5-Math.min(8,p.streak*2))}}).sort(()=>Math.random()-.5).sort((a,b)=>b.w-a.w).map(x=>x.q.id)}
  function pool(kind="learn"){
    let qs=safe();
    if(kind==="this-year")qs=qs.filter(q=>q.sourceType==="CURRENT_YEAR_SOURCE"||q.sourceType==="CURRENT_YEAR_VARIANT"||q.sourceType==="PROFESSOR_HINT");
    if(kind==="high-yield")qs=qs.filter(q=>q.priority>=4||q.sourceType==="SUPPORTING_HIGH_YIELD");
    if(kind==="mistakes")qs=qs.filter(q=>state.mistakes[q.id]);
    return weighted(qs);
  }
  function start(kind="learn",ids=null){const list=ids||pool(kind);session={ids:list,index:0,selected:null,excluded:[],submitted:false,kind,score:0,elimination:0};location.hash="learn";render()}
  function head(kicker,title,desc,action=""){return `<section class="hero"><div><div class="eyebrow">${esc(kicker)}</div><h1>${esc(title)}</h1><p class="muted">${esc(desc)}</p></div>${action}</section>`}
  function statusBadges(q){let badge=q.codexStatus==="APPROVED"?`<span class="badge green">✓ zatwierdzone przez Codex</span>`:q.codexStatus==="DIFFERS"?`<span class="badge red">Codex sugeruje ${q.codexAnswer} · klucz źródłowy ${q.sourceAnswer}</span>`:`<span class="badge amber">AI · wariant konceptu</span>`;return `<span class="badge">${esc(q.category)}</span><span class="badge">${esc(q.matrixAxis)}</span>${q.sourceType==="PROFESSOR_HINT"?`<span class="badge amber">★ wskazówka profesor</span>`:""}${q.sourceType==="CURRENT_YEAR_SOURCE"?`<span class="badge green">⚡ pytanie źródłowe 2025/26</span>`:""}${badge}`}
  function study(){
    if(!session||!session.ids.length)return `${head("FAST MODE","Ucz się teraz","Najpierw tegoroczne pytania, błędy i nieopanowane komórki macierzy.")}<div class="card empty"><h2>Gotowy?</h2><p>Klawiatura: 1–5 wybiera, Enter zatwierdza, Spacja oznacza „Nie wiem” i ujawnia odpowiedź.</p><button class="btn primary" data-start="learn">Rozpocznij</button></div>`;
    if(session.index>=session.ids.length)return summary();
    const q=qmap.get(session.ids[session.index]);if(!q)return "";const entries=Object.entries(q.answers),p=prog(q.id),source=q.sources?.[0];
    return `<div class="study"><div class="meta">${statusBadges(q)}</div><div class="card"><div class="muted">${session.index+1}/${session.ids.length} · ${esc(q.id)} · mastery ${Math.min(3,p.streak)}/3</div><h1 class="question">${esc(q.question)}</h1><div class="keys"><kbd>1–5</kbd> wybierz · <kbd>Enter</kbd> zatwierdź / dalej · <kbd>Spacja</kbd> nie wiem</div><div class="answers">${entries.map(([l,a],i)=>`<div class="answer-wrap"><button class="answer ${session.selected===l?"selected":""} ${session.submitted?(l===q.correctAnswer?"correct":session.selected===l?"wrong":""):""}" data-answer="${l}" ${session.submitted?"disabled":""}><span class="num">${i+1}</span><span><b>${l}.</b> ${esc(a)}</span></button><button class="exclude ${session.excluded.includes(l)?"on":""}" data-exclude="${l}" ${session.submitted?"disabled":""}>×</button>${session.submitted?`<div class="rationale ${l===q.correctAnswer?"good":"bad"}"><b>${l===q.correctAnswer?"Dlaczego prawidłowa:":"Dlaczego fałszywa:"}</b> ${esc(q.answerRationales?.[l]||`${l===q.correctAnswer?"Prawda":"Fałsz"} według klucza.`)}</div>`:""}</div>`).join("")}</div>${session.submitted?feedback(q):""}<div class="actions">${source?.file&&location.protocol==="file:"?`<a class="btn secondary" href="${esc(source.file)}${source.page?`#page=${source.page}`:""}" target="_blank">Źródło${source.page?` · str. ${source.page}`:""}</a>`:""}${!session.submitted?`<button class="btn secondary" data-dont-know>Nie wiem <kbd>Spacja</kbd></button>`:""}<button class="btn primary" data-enter>${session.submitted?"Następne":"Zatwierdź"} <kbd>Enter</kbd></button></div></div></div>`
  }
  function feedback(q){const ok=session.selected===q.correctAnswer,neighbors=safe().filter(x=>x.concept===q.concept&&x.id!==q.id).length;return `<div class="feedback ${ok?"good":"bad"}"><b>${ok?"Dobrze.":`Nie. Klucz źródłowy / treningowy: ${q.correctAnswer}.`}</b><p>${esc(q.answerRationales?.[q.correctAnswer]||q.answers[q.correctAnswer])}</p><div class="source-note"><b>Macierz alternatyw:</b> ${esc(q.concept)} · ${neighbors} sąsiednich wariantów. Błędne odpowiedzi pozostają częścią konceptu i mogą wrócić jako osobne pytania.</div>${q.sourceLabel?`<div class="source-note"><b>Pochodzenie:</b> ${esc(q.sourceLabel)}</div>`:""}</div>`}
  function submit(){if(!session||session.submitted||!session.selected)return;const q=qmap.get(session.ids[session.index]),p={...prog(q.id)},ok=session.selected===q.correctAnswer;const correctlyExcluded=session.excluded.filter(l=>l!==q.correctAnswer).length;p.attempts++;p.correct+=ok?1:0;p.wrong+=ok?0:1;p.streak=ok?p.streak+1:0;p.last=new Date().toISOString();state.progress[q.id]=p;state.xp+=ok?10+correctlyExcluded:correctlyExcluded;session.score+=ok?1:0;session.elimination+=correctlyExcluded;if(!ok)state.mistakes[q.id]={count:(state.mistakes[q.id]?.count||0)+1,lastSelected:session.selected,last:new Date().toISOString()};else if(state.mistakes[q.id]&&p.streak>=2)delete state.mistakes[q.id];session.submitted=true;save();render()}
  function next(){if(!session)return;if(!session.submitted){submit();return}session.index++;session.selected=null;session.excluded=[];session.submitted=false;render()}
  function dontKnow(){if(!session||session.submitted)return;const q=qmap.get(session.ids[session.index]),p={...prog(q.id)},correctlyExcluded=session.excluded.filter(l=>l!==q.correctAnswer).length;p.attempts++;p.wrong++;p.streak=0;p.last=new Date().toISOString();state.progress[q.id]=p;state.mistakes[q.id]={count:(state.mistakes[q.id]?.count||0)+1,lastSelected:null,last:new Date().toISOString(),reason:"Nie wiem"};state.xp+=correctlyExcluded;session.elimination+=correctlyExcluded;session.selected=null;session.submitted=true;save();render()}
  function summary(){return `${head("SESJA ZAKOŃCZONA","${session.score}/${session.ids.length}",`Punkty za poprawne eliminacje: ${session.elimination}. Błędy wróciły do priorytetowej puli.`)}<div class="card"><div class="actions"><button class="btn primary" data-start="mistakes">Napraw błędy</button><button class="btn secondary" data-start="learn">Nowa sesja</button></div></div>`}
  function landing(kind){const cfg={"this-year":["CURRENT YEAR","Tylko 2025/26","Pytania źródłowe, warianty tegorocznych konceptów i oznaczone wskazówki profesor."],"high-yield":["HIGH YIELD","Największy zwrot z czasu","Tegoroczne koncepty, wskazówki profesor i powtórzenia ze starszej bazy."],"mistakes":["ERROR BOOK","Moje błędy","Pytanie znika stąd po dwóch kolejnych poprawnych odpowiedziach."]}[kind];const ids=pool(kind),qs=ids.map(id=>qmap.get(id));return `${head(cfg[0],cfg[1],cfg[2],`<button class="btn primary" data-start="${kind}">Rozpocznij (${qs.length})</button>`)}<div class="list">${qs.slice(0,80).map(q=>`<article class="row"><div><h3>${esc(q.question)}</h3><div class="meta">${statusBadges(q)}</div></div><button class="btn secondary" data-one="${q.id}">Start</button></article>`).join("")||`<div class="card empty">Brak pytań w tej puli.</div>`}</div>`}
  function progressPage(){const m=metrics(),cats=[...new Set(safe().map(q=>q.category))];return `${head("LOCAL PROGRESS","Postęp","Coverage i mastery są liczone oddzielnie; wysoka skuteczność na małej puli nie udaje gotowości egzaminacyjnej.")}<div class="grid"><div class="card stat"><span>Coverage</span><strong>${m.coverage}%</strong><p>${m.seen}/${m.total} pytań widzianych</p></div><div class="card stat"><span>Skuteczność</span><strong>${m.accuracy??"—"}${m.accuracy===null?"":"%"}</strong><p>${m.attempts} wszystkich prób</p></div><div class="card stat"><span>Opanowane</span><strong>${m.mastered}</strong><p>3 poprawne z rzędu</p></div></div><div class="card" style="margin-top:18px"><h2>Działy</h2>${cats.map(c=>{const qs=safe().filter(q=>q.category===c),seen=qs.filter(q=>prog(q.id).attempts).length,pct=Math.round(seen/qs.length*100);return `<div style="margin:16px 0"><div style="display:flex;justify-content:space-between"><b>${esc(c)}</b><span>${seen}/${qs.length}</span></div><div class="progress"><i style="width:${pct}%"></i></div></div>`}).join("")}</div><div class="card danger-zone"><h2>RESETUJ PROGRES</h2><p>Kasuje postęp tylko tego użytkownika w tej przeglądarce. Baza pytań pozostaje.</p><button class="btn danger" data-reset>RESETUJ PROGRES</button></div>`}
  function render(){chrome();const r=(location.hash||"#learn").slice(1);$("#app").innerHTML=r==="learn"?study():r==="progress"?progressPage():landing(r in {"this-year":1,"high-yield":1,"mistakes":1}?r:"this-year");$("#app").focus({preventScroll:true})}
  document.addEventListener("click",e=>{const a=e.target.closest("[data-answer]");if(a&&!session?.submitted){session.selected=a.dataset.answer;render();return}const x=e.target.closest("[data-exclude]");if(x&&!session?.submitted){const l=x.dataset.exclude;session.excluded=session.excluded.includes(l)?session.excluded.filter(v=>v!==l):[...session.excluded,l];render();return}const st=e.target.closest("[data-start]");if(st){start(st.dataset.start);return}const one=e.target.closest("[data-one]");if(one){start("one",[one.dataset.one]);return}if(e.target.closest("[data-enter]")){next();return}if(e.target.closest("[data-dont-know]")){dontKnow();return}if(e.target.closest("[data-reset]")&&confirm("Na pewno wyzerować cały lokalny progres exam_FAST?")){state=defaultState();save();session=null;render()}});
  window.addEventListener("keydown",e=>{if(["INPUT","TEXTAREA","SELECT"].includes(document.activeElement?.tagName))return;if(/^Digit[1-5]$/.test(e.code)&&session&&!session.submitted){const q=qmap.get(session.ids[session.index]),l=Object.keys(q.answers)[Number(e.key)-1];if(l){session.selected=l;render()}e.preventDefault()}else if(e.code==="Enter"&&location.hash==="#learn"){next();e.preventDefault()}else if(e.code==="Space"&&location.hash==="#learn"&&session&&!session.submitted){dontKnow();e.preventDefault()}});
  window.addEventListener("hashchange",render);render();
})();
