(()=>{
  "use strict";
  const DATA=window.EXAM_FAST_DATA,DIAGRAMS=window.EXAM_FAST_DIAGRAMS||[], KEY="exam-fast-progress-v1", $=(s,r=document)=>r.querySelector(s), esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
  const defaultState=()=>({progress:{},mistakes:{},xp:0,bests:{},sound:false,started:new Date().toISOString()});
  let state;try{state={...defaultState(),...JSON.parse(localStorage.getItem(KEY)||"{}")}}catch{state=defaultState()}
  let session=null,timer=null;
  const save=()=>localStorage.setItem(KEY,JSON.stringify(state));
  const prog=id=>state.progress[id]||{attempts:0,correct:0,wrong:0,streak:0,last:null};
  const safe=()=>DATA.questions.filter(q=>q.correctAnswer&&q.answers?.[q.correctAnswer]);
  const qmap=new Map(DATA.questions.map(q=>[q.id,q]));
  function metrics(){const qs=safe(),seen=qs.filter(q=>prog(q.id).attempts),attempts=qs.reduce((n,q)=>n+prog(q.id).attempts,0),correct=qs.reduce((n,q)=>n+prog(q.id).correct,0),mastered=qs.filter(q=>prog(q.id).streak>=3);return{total:qs.length,seen:seen.length,coverage:Math.round(seen.length/qs.length*100),accuracy:attempts?Math.round(correct/attempts*100):null,mastered:mastered.length,attempts}}
  function chrome(){const m=metrics();$("#coverage").textContent=`Coverage ${m.coverage}%`;$("#accuracy").textContent=`Skuteczność ${m.accuracy??"—"}${m.accuracy===null?"":"%"}`;$("#xp").textContent=`⚡ ${state.xp||0} XP`;document.querySelectorAll(".nav a").forEach(a=>a.classList.toggle("active",location.hash.startsWith(a.hash)))}
  function weighted(pool){return pool.map(q=>{const p=prog(q.id),mist=state.mistakes[q.id]?.count||0;return{q,w:Math.max(1,(q.priority||1)*2+(p.attempts?0:12)+mist*5-Math.min(8,p.streak*2))}}).sort(()=>Math.random()-.5).sort((a,b)=>b.w-a.w).map(x=>x.q.id)}
  function pool(kind="learn"){
    let qs=safe();
    if(kind==="this-year")qs=qs.filter(q=>q.sourceType==="CURRENT_YEAR_SOURCE"||q.sourceType==="CURRENT_YEAR_VARIANT"||q.sourceType==="PROFESSOR_HINT");
    if(kind==="high-yield")qs=qs.filter(q=>q.priority>=4||q.sourceType==="SUPPORTING_HIGH_YIELD");
    if(kind==="mistakes")qs=qs.filter(q=>state.mistakes[q.id]);
    return weighted(qs);
  }
  function start(kind="learn",ids=null,limit=20,seconds=0){clearInterval(timer);const full=ids||pool(kind),list=ids?full:full.slice(0,Math.min(limit||full.length,full.length));session={ids:list,index:0,answered:0,selected:null,excluded:[],submitted:false,kind,score:0,elimination:0,combo:0,maxCombo:0,xp:0,wrongIds:[],startedAt:Date.now(),secondsLeft:seconds,timed:Boolean(seconds)};if(seconds){timer=setInterval(()=>{if(!session||!session.timed||session.index>=session.ids.length){clearInterval(timer);return}session.secondsLeft--;const el=$("#timer");if(el)el.textContent=clock(session.secondsLeft);if(session.secondsLeft<=0){clearInterval(timer);session.index=session.ids.length;render()}},1000)}location.hash="learn";render()}
  const clock=s=>`${Math.max(0,Math.floor(s/60))}:${String(Math.max(0,s%60)).padStart(2,"0")}`;
  function reward(ok,boss){if(navigator.vibrate)navigator.vibrate(ok?[18]:[35,35,35]);if(!state.sound)return;try{const C=window.AudioContext||window.webkitAudioContext,c=new C(),o=c.createOscillator(),g=c.createGain();o.connect(g);g.connect(c.destination);o.frequency.value=ok?(boss?880:660):190;g.gain.setValueAtTime(.035,c.currentTime);g.gain.exponentialRampToValueAtTime(.001,c.currentTime+.12);o.start();o.stop(c.currentTime+.12)}catch{}}
  function head(kicker,title,desc,action=""){return `<section class="hero"><div><div class="eyebrow">${esc(kicker)}</div><h1>${esc(title)}</h1><p class="muted">${esc(desc)}</p></div>${action}</section>`}
  function statusBadges(q){let badge=q.codexStatus==="APPROVED"?`<span class="badge green">✓ zatwierdzone przez Codex</span>`:q.codexStatus==="DIFFERS"?`<span class="badge red">Codex sugeruje ${q.codexAnswer} · klucz źródłowy ${q.sourceAnswer}</span>`:`<span class="badge amber">AI · wariant konceptu</span>`;return `<span class="badge">${esc(q.category)}</span><span class="badge">${esc(q.matrixAxis)}</span>${q.sourceType==="PROFESSOR_HINT"?`<span class="badge amber">★ wskazówka profesor</span>`:""}${q.sourceType==="CURRENT_YEAR_SOURCE"?`<span class="badge green">⚡ pytanie źródłowe 2025/26</span>`:""}${badge}`}
  function study(){
    if(!session||!session.ids.length)return `${head("FAST MODE","Ucz się teraz","Krótkie serie, natychmiastowa informacja zwrotna i powrót do błędów.")}<div class="mode-grid"><button class="mode-card" data-start="learn" data-limit="20"><b>⚡ Szybka sesja</b><strong>20 pytań</strong><span>Najlepszy balans tempa i powtórek</span></button><button class="mode-card" data-start="learn" data-limit="10"><b>🎯 Mikro sprint</b><strong>10 pytań</strong><span>Skończysz w kilka minut</span></button><button class="mode-card hot" data-start="high-yield" data-limit="999" data-seconds="300"><b>🔥 Sprint na czas</b><strong>5 minut</strong><span>Ile zdążysz bez utraty jakości?</span></button></div><div class="card quick-help"><b>Sterowanie:</b> 1–5 wybiera, Enter zatwierdza, Spacja oznacza „Nie wiem” i ujawnia odpowiedź. <button class="sound-toggle" data-sound>${state.sound?"🔊 Dźwięk włączony":"🔇 Włącz dźwięk"}</button></div>`;
    if(session.index>=session.ids.length)return summary();
    const q=qmap.get(session.ids[session.index]);if(!q)return "";const entries=Object.entries(q.answers),p=prog(q.id),source=q.sources?.[0],boss=(session.index+1)%10===0;
    return `<div class="study ${session.submitted?"answered":""}"><div class="gamebar"><span class="combo ${session.combo>=3?"lit":""}">🔥 COMBO <b>${session.combo}</b></span><span>⚡ <b>${session.xp}</b> XP</span>${session.timed?`<span class="timer">⏱ <b id="timer">${clock(session.secondsLeft)}</b></span>`:""}<span class="session-progress">${session.index+1}/${session.ids.length}</span></div><div class="session-track"><i style="width:${Math.round(session.index/session.ids.length*100)}%"></i></div>${boss?`<div class="boss-banner">👑 BOSS · podwójne XP</div>`:""}<div class="meta">${statusBadges(q)}</div><div class="card question-card"><div class="muted">${esc(q.id)} · mastery ${Math.min(3,p.streak)}/3</div><h1 class="question">${esc(q.question)}</h1><div class="keys"><kbd>1–5</kbd> wybierz · <kbd>Enter</kbd> zatwierdź / dalej · <kbd>Spacja</kbd> nie wiem</div><div class="answers">${entries.map(([l,a],i)=>`<div class="answer-wrap"><button class="answer ${session.selected===l?"selected":""} ${session.submitted?(l===q.correctAnswer?"correct":session.selected===l?"wrong":""):""}" data-answer="${l}" ${session.submitted?"disabled":""}><span class="num">${i+1}</span><span><b>${l}.</b> ${esc(a)}</span></button><button class="exclude ${session.excluded.includes(l)?"on":""}" data-exclude="${l}" ${session.submitted?"disabled":""}>×</button>${session.submitted?`<div class="rationale ${l===q.correctAnswer?"good":"bad"}"><b>${l===q.correctAnswer?"Dlaczego prawidłowa:":"Dlaczego fałszywa:"}</b> ${esc(q.answerRationales?.[l]||`${l===q.correctAnswer?"Prawda":"Fałsz"} według klucza.`)}</div>`:""}</div>`).join("")}</div>${session.submitted?feedback(q):""}<div class="actions">${source?.file&&location.protocol==="file:"?`<a class="btn secondary" href="${esc(source.file)}${source.page?`#page=${source.page}`:""}" target="_blank">Źródło${source.page?` · str. ${source.page}`:""}</a>`:""}${!session.submitted?`<button class="btn secondary" data-dont-know>Nie wiem <kbd>Spacja</kbd></button>`:""}<button class="btn primary" data-enter>${session.submitted?"Następne":"Zatwierdź"} <kbd>Enter</kbd></button></div></div></div>`
  }
  function feedback(q){const ok=session.selected===q.correctAnswer,neighbors=safe().filter(x=>x.concept===q.concept&&x.id!==q.id).length,boss=(session.index+1)%10===0;return `<div class="feedback ${ok?"good":"bad"}"><div class="reward-line"><b>${ok?`✓ Dobrze! +${session.lastGain} XP`:`Nie tym razem. Klucz: ${q.correctAnswer}.`}</b>${ok&&session.combo>=3?`<span>🔥 seria ${session.combo}</span>`:""}${ok&&boss?`<span>👑 BOSS pokonany</span>`:""}</div><p>${esc(q.answerRationales?.[q.correctAnswer]||q.answers[q.correctAnswer])}</p><div class="source-note"><b>Macierz alternatyw:</b> ${esc(q.concept)} · ${neighbors} sąsiednich wariantów. Błędne odpowiedzi pozostają częścią konceptu i mogą wrócić jako osobne pytania.</div>${q.sourceLabel?`<div class="source-note"><b>Pochodzenie:</b> ${esc(q.sourceLabel)}</div>`:""}</div>`}
  function submit(){if(!session||session.submitted||!session.selected)return;const q=qmap.get(session.ids[session.index]),p={...prog(q.id)},ok=session.selected===q.correctAnswer,boss=(session.index+1)%10===0;const correctlyExcluded=session.excluded.filter(l=>l!==q.correctAnswer).length;p.attempts++;p.correct+=ok?1:0;p.wrong+=ok?0:1;p.streak=ok?p.streak+1:0;p.last=new Date().toISOString();state.progress[q.id]=p;session.answered++;session.combo=ok?session.combo+1:0;session.maxCombo=Math.max(session.maxCombo,session.combo);const multiplier=boss?2:1,gain=ok?(10+Math.min(10,session.combo*2)+correctlyExcluded)*multiplier:correctlyExcluded;session.lastGain=gain;session.xp+=gain;state.xp+=gain;session.score+=ok?1:0;session.elimination+=correctlyExcluded;if(!ok){state.mistakes[q.id]={count:(state.mistakes[q.id]?.count||0)+1,lastSelected:session.selected,last:new Date().toISOString()};if(!session.wrongIds.includes(q.id))session.wrongIds.push(q.id)}else if(state.mistakes[q.id]&&p.streak>=2)delete state.mistakes[q.id];session.submitted=true;reward(ok,boss);save();render()}
  function next(){if(!session)return;if(!session.submitted){submit();return}session.index++;session.selected=null;session.excluded=[];session.submitted=false;render()}
  function dontKnow(){if(!session||session.submitted)return;const q=qmap.get(session.ids[session.index]),p={...prog(q.id)},correctlyExcluded=session.excluded.filter(l=>l!==q.correctAnswer).length;p.attempts++;p.wrong++;p.streak=0;p.last=new Date().toISOString();state.progress[q.id]=p;state.mistakes[q.id]={count:(state.mistakes[q.id]?.count||0)+1,lastSelected:null,last:new Date().toISOString(),reason:"Nie wiem"};state.xp+=correctlyExcluded;session.answered++;session.xp+=correctlyExcluded;session.elimination+=correctlyExcluded;session.combo=0;session.lastGain=correctlyExcluded;if(!session.wrongIds.includes(q.id))session.wrongIds.push(q.id);session.selected=null;session.submitted=true;reward(false,false);save();render()}
  function summary(){clearInterval(timer);const total=session.answered,elapsed=Math.max(1,Math.round((Date.now()-session.startedAt)/1000)),accuracy=total?Math.round(session.score/total*100):0,key=session.timed?"sprint5":`q${session.ids.length}`,best=state.bests[key]||{score:0,accuracy:0};if(session.score>best.score||(session.score===best.score&&accuracy>best.accuracy))state.bests[key]={score:session.score,accuracy,at:new Date().toISOString()};save();return `${head("SESJA ZAKOŃCZONA",`${session.score}/${total||0}`,`${accuracy}% poprawnych · max combo ${session.maxCombo} · ${session.xp} XP · ${clock(elapsed)}`)}<div class="result-grid"><div class="card result"><span>Zdobyte XP</span><strong>+${session.xp}</strong></div><div class="card result"><span>Najdłuższa seria</span><strong>🔥 ${session.maxCombo}</strong></div><div class="card result"><span>Rekord trybu</span><strong>${state.bests[key].score}</strong></div></div><div class="card"><div class="actions">${session.wrongIds.length?`<button class="btn primary" data-repair>Napraw ${session.wrongIds.length} ${session.wrongIds.length===1?"błąd":"błędów"}</button>`:""}<button class="btn secondary" data-start="learn" data-limit="5">Jeszcze 5 pytań</button><button class="btn secondary" data-home>Wybierz tryb</button></div></div>`}
  function landing(kind){const cfg={"this-year":["CURRENT YEAR","Tylko 2025/26","Pytania źródłowe, warianty tegorocznych konceptów i oznaczone wskazówki profesor."],"high-yield":["HIGH YIELD","Największy zwrot z czasu","Tegoroczne koncepty, wskazówki profesor i powtórzenia ze starszej bazy."],"mistakes":["ERROR BOOK","Moje błędy","Pytanie znika stąd po dwóch kolejnych poprawnych odpowiedziach."]}[kind];const ids=pool(kind),qs=ids.map(id=>qmap.get(id));return `${head(cfg[0],cfg[1],cfg[2],`<button class="btn primary" data-start="${kind}">Rozpocznij (${qs.length})</button>`)}<div class="list">${qs.slice(0,80).map(q=>`<article class="row"><div><h3>${esc(q.question)}</h3><div class="meta">${statusBadges(q)}</div></div><button class="btn secondary" data-one="${q.id}">Start</button></article>`).join("")||`<div class="card empty">Brak pytań w tej puli.</div>`}</div>`}
  function diagramsPage(id){const d=DIAGRAMS.find(x=>x.id===id);if(d){const q=qmap.get(d.questionId);return `${head("VISUAL FAST",d.title,d.caption,`<button class="btn secondary" data-diagrams>← Wszystkie schematy</button>`)}<div class="diagram-detail card"><div class="diagram-canvas">${d.svg}</div><div class="diagram-question"><span class="badge">${esc(d.category)}</span><h2>${esc(q?.question||"Pytanie do schematu")}</h2><p class="muted">Najpierw odczytaj schemat, następnie rozwiąż pełne pytanie z uzasadnieniem każdego wariantu.</p><button class="btn primary" data-one="${esc(d.questionId)}">Rozwiąż pytanie →</button></div></div>`}return `${head("VISUAL FAST","Schematy","Najważniejsze zależności w formie obrazu. Każdy schemat prowadzi bezpośrednio do pytania z bazy FAST.")}<div class="diagram-grid">${DIAGRAMS.map(x=>`<button class="diagram-card" data-diagram="${esc(x.id)}"><div class="diagram-thumb">${x.svg}</div><div><span>${esc(x.category)}</span><h2>${esc(x.title)}</h2><p>${esc(x.caption)}</p><b>Zobacz i rozwiąż →</b></div></button>`).join("")}</div>`}
  function progressPage(){const m=metrics(),cats=[...new Set(safe().map(q=>q.category))];return `${head("LOCAL PROGRESS","Postęp","Coverage i mastery są liczone oddzielnie; wysoka skuteczność na małej puli nie udaje gotowości egzaminacyjnej.")}<div class="grid"><div class="card stat"><span>Coverage</span><strong>${m.coverage}%</strong><p>${m.seen}/${m.total} pytań widzianych</p></div><div class="card stat"><span>Skuteczność</span><strong>${m.accuracy??"—"}${m.accuracy===null?"":"%"}</strong><p>${m.attempts} wszystkich prób</p></div><div class="card stat"><span>Opanowane</span><strong>${m.mastered}</strong><p>3 poprawne z rzędu</p></div></div><div class="card" style="margin-top:18px"><h2>Działy</h2>${cats.map(c=>{const qs=safe().filter(q=>q.category===c),seen=qs.filter(q=>prog(q.id).attempts).length,pct=Math.round(seen/qs.length*100);return `<div style="margin:16px 0"><div style="display:flex;justify-content:space-between"><b>${esc(c)}</b><span>${seen}/${qs.length}</span></div><div class="progress"><i style="width:${pct}%"></i></div></div>`}).join("")}</div><div class="card danger-zone"><h2>RESETUJ PROGRES</h2><p>Kasuje postęp tylko tego użytkownika w tej przeglądarce. Baza pytań pozostaje.</p><button class="btn danger" data-reset>RESETUJ PROGRES</button></div>`}
  function render(){chrome();const r=(location.hash||"#learn").slice(1),[page,id]=r.split("/");$("#app").innerHTML=page==="learn"?study():page==="progress"?progressPage():page==="diagrams"?diagramsPage(id):landing(page in {"this-year":1,"high-yield":1,"mistakes":1}?page:"this-year");$("#app").focus({preventScroll:true})}
  document.addEventListener("click",e=>{const a=e.target.closest("[data-answer]");if(a&&!session?.submitted){session.selected=a.dataset.answer;render();return}const x=e.target.closest("[data-exclude]");if(x&&!session?.submitted){const l=x.dataset.exclude;session.excluded=session.excluded.includes(l)?session.excluded.filter(v=>v!==l):[...session.excluded,l];render();return}const st=e.target.closest("[data-start]");if(st){start(st.dataset.start,null,Number(st.dataset.limit||20),Number(st.dataset.seconds||0));return}const one=e.target.closest("[data-one]");if(one){start("one",[one.dataset.one],1);return}const dia=e.target.closest("[data-diagram]");if(dia){location.hash=`diagrams/${dia.dataset.diagram}`;return}if(e.target.closest("[data-diagrams]")){location.hash="diagrams";return}if(e.target.closest("[data-enter]")){next();return}if(e.target.closest("[data-dont-know]")){dontKnow();return}if(e.target.closest("[data-repair]")){start("repair",session.wrongIds,session.wrongIds.length);return}if(e.target.closest("[data-home]")){clearInterval(timer);session=null;render();return}if(e.target.closest("[data-sound]")){state.sound=!state.sound;save();render();return}if(e.target.closest("[data-reset]")&&confirm("Na pewno wyzerować cały lokalny progres exam_FAST?")){state=defaultState();save();session=null;render()}});
  window.addEventListener("keydown",e=>{if(["INPUT","TEXTAREA","SELECT"].includes(document.activeElement?.tagName))return;if(/^Digit[1-5]$/.test(e.code)&&session&&!session.submitted){const q=qmap.get(session.ids[session.index]),l=Object.keys(q.answers)[Number(e.key)-1];if(l){session.selected=l;render()}e.preventDefault()}else if(e.code==="Enter"&&location.hash==="#learn"){next();e.preventDefault()}else if(e.code==="Space"&&location.hash==="#learn"&&session&&!session.submitted){dontKnow();e.preventDefault()}});
  window.addEventListener("hashchange",render);render();
})();
